<a href="https://colab.research.google.com/github/sakshitiwari1234/Machine-Learning/blob/main/K_Fold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### K fold cross validation.

in k fold cross validation technique is used to find the average best answer of fiting any model into regression and classification dataset and checking it's accuracy.

the dataset is always divided into some ratio to check the score after fitting the model, in some 80 and 20 percent , but the technique to find the best fitted model is desribed in k fold validation technique.

in this , the sample data is divided into various subparts equally called folds. each of the subpart data is taken as a train and tested data that is, if one part is taken as testing the data nd rest used as training ddata , this iteration keeps on going and performed with every data and then , the average of all the traintest split of all subset is taken into account and considered.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(digits.data, digits.target,test_size=0.3)

In [ ]:
lr = LogisticRegression()
lr.fit(xtrain,ytrain)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
 lr.score(xtest, ytest)

0.9703703703703703

In [ ]:
svm = SVC()
import numpy as np
svm.fit(xtrain, ytrain)
svm.score(xtest,ytest)

0.9888888888888889

In [ ]:
rf = RandomForestClassifier(n_estimators = 40)
rf.fit(xtrain,ytrain)
rf.score(xtest, ytest)

0.9685185185185186

In [ ]:
# now trying the k-fold methods
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8]):
  print (train_index, test_index)

[3 4 5 6 7] [0 1 2]
[0 1 2 6 7] [3 4 5]
[0 1 2 3 4 5] [6 7]


In [ ]:
def get_score (model, xtrain, xtest,ytrain, ytest):
  model.fit(xtrain, ytrain)
  return model.score(xtest, ytest)

In [ ]:
get_score(LogisticRegression(),xtrain,xtest,ytrain,ytest)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9703703703703703

In [ ]:
get_score(SVC(), xtrain,xtest,ytrain, ytest)

0.9888888888888889

In [ ]:
from sklearn.model_selection import   StratifiedKFold
folds = StratifiedKFold(n_splits = 3)


In [ ]:
score_l = []
score_svm = []
score_rf = []

for train_index, test_index in kf.split(digits.data):
  xtrain,ytrain,ytest,xtest= digits.data[train_index], digits.data[test_index],digits.target[train_index], digits.target[test_index]
  # score_l.append(get_score(LogisticRegression(), xtrain,xtest,ytrain,ytest))
  score_svm.append(get_score(SVC(), xtrain,xtest,ytrain,ytest))
  score_rf.append(get_score(RandomForestClassifier(), xtrain,xtest,ytrain,ytest))


ValueError: y should be a 1d array, got an array of shape (599, 64) instead.

In [ ]:
score_l

[]

In [ ]:
score_rf

[]

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [ ]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=15),digits.data, digits.target)

array([0.93055556, 0.87222222, 0.93314763, 0.93871866, 0.92200557])

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target)

array([0.93611111, 0.91111111, 0.94986072, 0.96100279, 0.94428969])