<a href="https://colab.research.google.com/github/sakshitiwari1234/Machine-Learning/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
revenue = np.array([[180, 200 , 220],[24,36,40],[12,18,20]])

expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [8]:
revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [10]:
expenses

array([[ 80,  90, 100],
       [ 10,  16,  20],
       [  8,  10,  10]])

In [11]:
profit = revenue - expenses

In [12]:
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [13]:
price = np.array([1000,400,1200])


In [17]:
price_per_unit = price* expenses

In [18]:
price_per_unit

array([[ 6400,  8100, 10000],
       [  100,   256,   400],
       [   64,   100,   100]])

In [20]:
ans = np.dot(price, expenses)

In [21]:
ans

array([[ 8100,  9640, 10800],
       [ 1120,  1356,  1520],
       [  820,   980,  1100]])

In [29]:


y_pred = np.array([1,1,0,0,1])
y_true = np.array([0,30,0,7,1])

In [23]:
def mae(y_true , y_pred):
  total_err = 0
  for yt , yp in zip(y_true , y_pred):
    total_err += abs(yt-yp)
  print("Total eorror" , total_err)

  mae = total_err / len(y_true)
  print(mae)
  return mae

In [24]:
mae(y_true , y_pred)

Total eorror 37.0
5.285714285714286


np.float64(5.285714285714286)

In [32]:
np.sum(np.abs(y_pred - y_true))

np.int64(37)